AWSTemplateFormatVersion: 2010-09-09
Description: Resources for the frontend part of MAJO21  
Parameters: 
  SiteBucketName:
    Type: String
    Default: majo21-fe
  SiteBetaBucketName:
    Type: String
    Default: majo21-fe-beta
  GithubUser:
    Type: String
    Default: yennlou
  GithubRepo:
    Type: String
    Default: majo21-web
  GithubBranch:
    Type: String
    Default: master
  GithubToken:
    Description: Go to https://github.com/settings/tokens
    NoEcho: true
    Type: String
  BuildType:
    Type: String
    Default: LINUX_CONTAINER
  BuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
  BuildImage:
    Type: String
    Default: 'aws/codebuild/amazonlinux2-x86_64-standard:2.0'
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: "codebuild-service"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Policies:
        - PolicyName: "codepipeline-service"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "codebuild:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                Resource: "*"
              - Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::codepipeline*'
              - Effect: Allow
                Action:
                  - 's3:*'
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                Resource: '*'
  SiteBetaBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref SiteBetaBucketName
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
            AllowedHeaders:
              - Authorization
              - Content-Length
      WebsiteConfiguration:
        IndexDocument: index.html
  SiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref SiteBucketName
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
            AllowedHeaders:
              - Authorization
              - Content-Length
      WebsiteConfiguration:
        IndexDocument: index.html
  PipelineBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
  CodeBuildDeploySiteBeta:
    Type: 'AWS::CodeBuild::Project'
    DependsOn: CodeBuildRole
    Properties:
      Name: !Sub '${AWS::StackName}-deploy-beta'
      Description: Deploy site beta to S3
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref BuildType
        ComputeType: !Ref BuildComputeType
        Image: !Sub '${BuildImage}'
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 12
              commands:
                - npm install yargs
            post_build:
              commands:
                - aws s3 rm s3://${SiteBetaBucketName} --recursive
                - node bin/deploySite.js deploy --dirPath=dist-dev --bucketName=${SiteBucketName}
                - echo Deployment completed on `date`
      TimeoutInMinutes: 10
  CodeBuildDeploySite:
    Type: 'AWS::CodeBuild::Project'
    DependsOn: CodeBuildRole
    Properties:
      Name: !Sub '${AWS::StackName}-deploy'
      Description: Deploy site to S3
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref BuildType
        ComputeType: !Ref BuildComputeType
        Image: !Sub '${BuildImage}'
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 12
              commands:
                - npm install yargs
            post_build:
              commands:
                - aws s3 rm s3://${SiteBucketName} --recursive
                - node bin/deploySite.js deploy --dirPath=dist-prod --bucketName=${SiteBucketName}
                - echo Deployment completed on `date`
      TimeoutInMinutes: 10
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: majo21-fe-pipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages: 
        - Name: Source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceArtifacts
              Configuration:
                Owner: !Ref GithubUser
                Repo: !Ref GithubRepo
                Branch: !Ref GithubBranch
                OAuthToken: !Ref GithubToken
              RunOrder: 1
        - Name: DeployBeta
          Actions:
            - Name: Artifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifacts
              OutputArtifacts:
                - Name: DeploymentBetaArtifacts
              Configuration:
                ProjectName: !Ref CodeBuildDeploySiteBeta
              RunOrder: 1
        - Name: ManualApproval
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: '1'
                Provider: Manual
              RunOrder: 1
        - Name: DeployProd
          Actions:
            - Name: Artifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifacts
              OutputArtifacts:
                - Name: DeploymentArtifacts
              Configuration:
                ProjectName: !Ref CodeBuildDeploySite
              RunOrder: 1

      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
Outputs: 
  PipelineUrl:
    Description: CodePipeline URL
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
  SiteBetaUrl:
    Description: MAJO21 BETA URL
    Value: !GetAtt SiteBetaBucket.WebsiteURL
  SiteUrl:
    Description: MAJO21 URL
    Value: !GetAtt SiteBucket.WebsiteURL
