const GalleryActionTypes = {
  FETCH_COLLECTION_START: 'GALLERY_FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'GALLERY_FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE: 'GALLERY_FETCH_COLLECTION_FAILURE'
}

export default GalleryActionTypes
