const COLORS = {
  CABARET: '#D3496B',
  LOCHMARA: '#2D72A3',
  BLACKRUSSIAN: '#181B2C',
  MIDNIGHTEXPRESS: '#1B2032',
  WHITESMOKE: '#F5F5F5',
  LUCKY: '#B39A1D'
}

const COLOR_THEME = {
  BG: COLORS.MIDNIGHTEXPRESS,
  SIDEBAR_BG: COLORS.BLACKRUSSIAN,
  SIDEBAR_FONT: COLORS.CABARET,
  NAV_FONT: COLORS.CABARET,
  SEARCH_BG: COLORS.MIDNIGHTEXPRESS,
  SEARCH_FONT: COLORS.LOCHMARA,
  BLOG_BORDER: COLORS.LOCHMARA,
  BLOG_FONT: COLORS.LOCHMARA,
  MD_FONT: COLORS.LOCHMARA,
  BLOG_LINK: COLORS.MIDNIGHTEXPRESS,
  BLOG_LINK_BG: COLORS.LOCHMARA,
  BLOG_STRONG: COLORS.LUCKY,
  BLOG_CODE: COLORS.LUCKY,
  BLOG_CODE_BG: COLORS.BLACKRUSSIAN,
  PAGINATION: COLORS.LOCHMARA,
  PAGINATION_ACTIVE: COLORS.LOCHMARA,
  PAGINATION_DISABLED: COLORS.LOCHMARA
}

export default {
  title: 'default:dark',
  type: 'color',
  pallete: COLORS,
  data: {
    ...COLOR_THEME
  }
}
