const COLORS = {
  CERISE: '#E62963',
  CERULEAN: '#0D70A5',
  BLACKRUSSIAN: '#191A2C',
  MIDNIGHTEXPRESS: '#1B1E33'
}

const COLOR_THEME = {
  BG: COLORS.MIDNIGHTEXPRESS,
  SIDEBAR_BG: COLORS.BLACKRUSSIAN,
  SIDEBAR_FONT: COLORS.CERISE,
  MENU_FONT: COLORS.CERISE,
  SEARCH_BG: COLORS.BLACKRUSSIAN,
  BLOG_BORDER: COLORS.CERULEAN,
  BLOG_FONT: COLORS.CERULEAN
}

export default {
  title: 'default:dark',
  type: 'color',
  data: {
    ...COLOR_THEME
  }
}
