const COLORS = {
  CABARET: '#D3496B',
  LOCHMARA: '#2D72A3',
  WHITESMOKE: '#F5F5F5',
  WHITE: '#FFFFFF',
  BLACKRUSSIAN: '#181B2C'
}

const COLOR_THEME = {
  BG: COLORS.WHITE,
  SIDEBAR_BG: COLORS.WHITESMOKE,
  SIDEBAR_FONT: COLORS.CABARET,
  NAV_FONT: COLORS.CABARET,
  SEARCH_BG: COLORS.WHITESMOKE,
  BLOG_BORDER: COLORS.LOCHMARA,
  BLOG_FONT: COLORS.LOCHMARA
}

export default {
  title: 'default:light',
  type: 'color',
  pallete: COLORS,
  data: {
    ...COLOR_THEME
  }
}
