const COLORS = {
  CABARET: '#D3496B',
  LOCHMARA: '#3a92d0',
  WHITESMOKE: '#F5F5F5',
  WHITE: '#FFFFFF',
  BLACKRUSSIAN: '#181B2C',
  LUCKY: '#e4a719'
}

const COLOR_THEME = {
  BG: COLORS.WHITE,
  SIDEBAR_BG: COLORS.WHITESMOKE,
  SIDEBAR_FONT: COLORS.CABARET,
  NAV_FONT: COLORS.CABARET,
  SEARCH_BG: COLORS.WHITESMOKE,
  BLOG_BORDER: COLORS.LOCHMARA,
  BLOG_FONT: COLORS.LOCHMARA,
  BLOG_LINK: COLORS.WHITE,
  BLOG_LINK_BG: COLORS.LOCHMARA,
  BLOG_STRONG: COLORS.CABARET,
  BLOG_CODE: COLORS.LUCKY,
  BLOG_CODE_BG: COLORS.WHITESMOKE,
  PAGINATION: COLORS.LOCHMARA,
  PAGINATION_ACTIVE: COLORS.LOCHMARA,
  PAGINATION_DISABLED: COLORS.LOCHMARA
}

export default {
  title: 'default:light',
  type: 'color',
  pallete: COLORS,
  data: {
    ...COLOR_THEME
  }
}
