version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Serverless...
      - npm install -g serverless@latest
  pre_build:
    commands:
      - echo Install source NPM dependencies
      - cd serverless
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless Framework
      - npx sls deploy -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`