version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Install source NPM dependencies
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./dist s3://${SiteBucketName}/
      - echo Deployment completed on `date`