service: blog-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  memorySize: 128
  timeout: 5
  environment:
    BLOG_TABLE: ${self:service}-${self:provider.stage}

resources:
  Resources:
    BlogTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.BLOG_TABLE}
        AttributeDefinitions:
          - AttributeName: post_type
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: post_id
            AttributeType: S
        KeySchema:
          - AttributeName: post_type
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: post_id-index
            KeySchema:
              - AttributeName: post_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 1
              