service: blog-backend

package:
  excludeDevDependencies: true

plugins:
  - serverless-dynamodb-local
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  endpoints:
    dynamodb-url: 'http://localhost:3000'
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  dotenv:
    path: ../personal/config/dev.env

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  memorySize: 128
  timeout: 5
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    DYNAMODB_ENDPOINT_LOCAL: ${self:custom.endpoints.dynamodb-url}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  get-posts:
    handler: api/getPosts.handler
    description: Get posts by type
    events:
      - http:
          path: posts/t/blog
          method: get
          cors: true
  load-posts:
    handler: api/loadPosts.handler
    description: Load posts from github
  update-on-github-push:
    handler: api/updateOnGithubPush.handler
    description: update posts on github push
    events:
      - http:
          path: webhooks/github/e/push
          method: post
    
resources:
  Resources:
    BlogTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: post_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: post_type
            AttributeType: S
          - AttributeName: path
            AttributeType: S
        KeySchema:
          - AttributeName: post_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: post_type-index
            KeySchema:
              - AttributeName: post_type
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 2
          - IndexName: post_path-index
            KeySchema:
              - AttributeName: path
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 2
              WriteCapacityUnits: 1

              