const BlogActionTypes = {
  FETCH_COLLECTION_START: 'BLOG_FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'BLOG_FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE: 'BLOG_FETCH_COLLECTION_FAILURE'
}

export default BlogActionTypes
